# This is a basic workflow to help you get started with Actions

name: self-ali

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, ali] 

    steps:
      - uses: actions/checkout@v4
        env:
          http_proxy: http://127.0.0.1:20171
          https_proxy: http://127.0.0.1:20171

      - name: Run a one-line script
        run: |
          curl --max-time 10 ip.sb
        env:
          http_proxy: http://127.0.0.1:20171
          https_proxy: http://127.0.0.1:20171

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          curl --max-time 10 ip.sb
          curl --proxy http://127.0.0.1:20171 --max-time 10 ip.sb
          
