
name: self docker 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/horacecuiorg/dockerfile/ubuntu2204:dockernode  # ← 使用你构建并上传的自定义镜像
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock  # ← 挂载宿主 Docker
      options: --privileged  # 如果需要运行 docker buildx，也可以添加

    steps:
      - name: 查看信息
        run: |
          whoami
          pwd
          ls -al /



      - uses: actions/checkout@v4

      - name: Verify Docker and Node
        run: |
          docker version
          docker ps
          node -v
          npm -v
